import LegalLayout from "../../components/LegalLayout";

const TermsOfService = () => {
  const lastUpdated = "October 24, 2026";
  const sections = [
    { id: "acceptance", label: "Acceptance of Terms" },
    { id: "use-license", label: "Use License" },
    { id: "user-responsibilities", label: "User Responsibilities" },
    { id: "ai-tools", label: "AI & Cloud Tools" },
    { id: "disclaimer", label: "Disclaimer of Warranties" },
    { id: "limitation", label: "Limitation of Liability" }
  ];

  return (
    <LegalLayout title="Terms of Service" lastUpdated={lastUpdated} sections={sections}>
      <h2 id="acceptance">1. Acceptance of Terms</h2>
      <p>
        By accessing and using <strong>UtilityHub</strong>, you accept and agree to be bound by the terms and provision of this agreement. 
        In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services. 
        Any participation in this service will constitute acceptance of this agreement. If you do not agree to abide by the above, please do not use this service.
      </p>

      <h2 id="use-license">2. Use License</h2>
      <p>
        Permission is granted to temporarily download one copy of the materials (information or software) on UtilityHub for personal, non-commercial transitory viewing only. 
        This is the grant of a license, not a transfer of title, and under this license you may not:
      </p>
      <ul>
        <li>Modify or copy the materials beyond standard browser caching;</li>
        <li>Use the materials for any commercial purpose, or for any public display (commercial or non-commercial) without attributing the source;</li>
        <li>Attempt to decompile or reverse engineer any software contained on UtilityHub;</li>
        <li>Remove any copyright or other proprietary notations from the materials; or</li>
        <li>Transfer the materials to another person or "mirror" the materials on any other server.</li>
      </ul>
      <p>
        This license shall automatically terminate if you violate any of these restrictions and may be terminated by UtilityHub at any time.
      </p>

      <h2 id="user-responsibilities">3. User Responsibilities</h2>
      <p>
        Because UtilityHub primarily operates as an offline, client-side application, <strong>you are solely responsible for the data you process.</strong> 
        We do not store backups of the files you convert, the text you generate, or the code you write.
      </p>
      <p>
        You agree not to use the tools provided to:
      </p>
      <ul>
        <li>Process illegal, explicit, or highly sensitive confidential material where strict compliance (like HIPAA) is legally required.</li>
        <li>Generate malicious code, malware, or destructive payloads.</li>
        <li>Attempt to overload the service through automated scraping or abuse of our APIs.</li>
      </ul>

      <h2 id="ai-tools">4. AI & Cloud Tools</h2>
      <p>
        Certain features within UtilityHub utilize third-party APIs (such as the Google Gemini API). 
        By using these specific AI features, you agree that your input prompts and files will be processed by these third-party services in accordance with their respective Terms of Service.
        UtilityHub is not responsible for the accuracy, reliability, or appropriateness of the output generated by these AI models.
      </p>

      <h2 id="disclaimer">5. Disclaimer of Warranties</h2>
      <p>
        The materials on UtilityHub's website are provided on an 'as is' basis. 
        UtilityHub makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
      </p>
      <p>
        Furthermore, UtilityHub does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.
      </p>

      <h2 id="limitation">6. Limitation of Liability</h2>
      <p>
        In no event shall UtilityHub or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on UtilityHub, even if UtilityHub or an authorized representative has been notified orally or in writing of the possibility of such damage. 
        Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
      </p>
    </LegalLayout>
  );
};

export default TermsOfService;
